### ISSUE TITLE
test functions

### ISSUE THREAD

**Issue by danielwilhelm** [danielwilhelm/STATA-NPIV#1]
we need a separate directory that contains functions testing the code
- these should be functions that simulate an NPIV model and then compare the output from the code with the truth

**Comment by dongwookim1984** [comment]
Several test do files are written.

**Comment by danielwilhelm** [comment]
Suggestions for tests:
1. simulate many MC samples
2. plot estimated function averaged over all MC samples, together with empirical standard deviation
3. compute mean integrated square error for estimator
