### ISSUE TITLE
basis functions

### ISSUE THREAD

**Issue by danielwilhelm** [danielwilhelm/STATA-NPIV#2]
npivreg should
- allow for argument that selects which basis to use ("B-spline", "polynomial", ...)
- use separate function for generating basis depending on above argument (generate the P,Q matrices)
- allow for user to specify degree of polynomials, number of knots

**Comment by dongwookim1984** [comment]
Now users can specify the number of knots and the power for basis functions. If those options left unspecified, then default setting runs. The type of basis function is also possible to choose between bspline and polynomial spline.

**Comment by danielwilhelm** [comment]
cubic B-spline  for both bases should be default
