### ISSUE TITLE
*: 3900 unable to allocate real

### ISSUE THREAD

**Issue by FelixStips** [danielwilhelm/STATA-NPIV#5]
First of all thank you for providing this extremely useful package!

I tried using it on a small data (n=200) and it worked without problems. Now, I am using it with larger datasets (n=800000, which is not even that large compared to other datasets I use) and receive the error:

*: 3900 unable to allocate real <tmp> [752884,752884]
npiv_estimation(): - function returned error
<ismt>: - function returned error

Browsing through Statalist seemed to suggest that the error is due to RAM issues. I asked IT in our department to increase it to 1024GB and tried again, the same error occurred.

Do you perhaps have an idea why this is occurring? What is the large matrix that mata is trying to create?

**Comment by FelixStips** [comment]
Indeed, it seems that I can run regressions up to 400k observations. Its strange that memory increases that much, isnt it?

**Comment by danielwilhelm** [comment]
Thank you for your interest in our new STATA command. We wrote a short paper for the STATA journal explaining the new command and the underlying estimator: [https://journals.sagepub.com/doi/pdf/10.1177/1536867X1801800411](https://journals.sagepub.com/doi/pdf/10.1177/1536867X1801800411). The unconstraint and constraint estimators are shown in equations (2) and (3). The matrices P and Q are of dimensions n-by-K and n-by-J, where n is the sample size; i.e. these are both large matrices when n is large. 

Of course, it is possible that there exists a computationally more efficient implementation that uses less RAM ...

**Comment by FelixStips** [comment]
Okay, thank you!
